# Generated by Django 5.1.4 on 2025-01-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_morador_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='cpf',
            field=models.CharField(max_length=16),
        ),
    ]
