# Generated by Django 5.1.4 on 2025-01-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_morador_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileexample',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
